### ISSUE TITLE
Some problems about demo.py

### ISSUE THREAD

**Issue by kingyue737** [morefigs/py-ic-imaging-control#29]
1.   snap_image always returns an error

2.  cam.create_frame_filter works well in my 64-bit python, but in 32-bit python it causes the error:

Traceback (most recent call last):
  File "E:/Program Files/JetBrains/PyProject/demo2.py", line 30, in <module>
    cam.add_frame_filter_to_device(h)
  File "E:\Program Files\Python\Python36-32\lib\site-packages\py_ic_imaging_control-1.0-py3.6.egg\pyicic\IC_Camera.py", line 336, in add_frame_filter_to_device
OSError: exception: access violation writing 0x5C16F9CC

3. i don't understand what's the meaning of "cam.register_frame_ready_callback"

Any idea about how to  solve these problems?

**Comment by morefigs** [comment]
What error is returned from `snap_image`?

A callback function is a function that is passed to the driver and automatically called when the driver is ready to call it, in this case when the frame is ready. The default callback function when called will set some flags that `wait_til_frame_ready` will wait to be set, which then allows access to the frame.

**Comment by kingyue737** [comment]
Thank you for your reply.

Here is the error:

Traceback (most recent call last):
  File "E:/Program Files/JetBrains/PyProject/demo2.py", line 59, in <module>
    cam.snap_image(1000)
  File "E:\Program Files\Python\Python36-32\lib\site-packages\py_ic_imaging_control-1.0-py3.6.egg\pyicic\IC_Camera.py", line 427, in snap_image
pyicic.IC_Exception.IC_Exception: 0


Why the function ‘handle_frame(handle_ptr, p_data, frame_num, data)’ is not used in the demo.py?

It also seems that the live mode in python has a much longer ‘exposure time’ and lower FPS than that in the official software of IC Capture. 


I don’t learn C++. Maybe I need some time to understand the official examples.

**Comment by nikhil4595** [comment]
@morefigs  

I was able to save images a few times, but suddenly I go the same error 

Traceback (most recent call last):
  File "C:/Users/z003kpue/PycharmProjects/untitled2/py-ic-imaging-control-master/demo.py", line 49, in <module>
    cam.snap_image(1000)
  File "C:\Users\z003kpue\PycharmProjects\untitled2\py-ic-imaging-control-master\pyicic\IC_Camera.py", line 427, in snap_image
    raise IC_Exception(err)
pyicic.IC_Exception.IC_Exception: 0

Any idea why this occured, I removed the device ,reinstalled the drivers as well, but nothing changed.

**Comment by morefigs** [comment]
I don't actually have one of these cameras anymore so it's hard for me to test.

**Comment by kingyue737** [comment]
Closed as stale. This was my first issue opened on GitHub. Thanks for this repo which helped me finish my internship six years ago.
