### ISSUE TITLE
module cannot be found

### ISSUE THREAD

**Issue by devinpatell** [morefigs/py-ic-imaging-control#30]
Hello, I have copied the pyicic directory into my working directory and tried to add it to my existing python files. When I try `from pyicic.IC_ImagingControl import *` it causes the following error.

`[Command: python -u 'C:\Users\<USERNAME>\Documents\Vision project\ball.py']
Traceback (most recent call last):
  File "C:\Users\<USERNAME>\Documents\Vision project\ball.py", line 4, in <module>
    from pyicic.IC_ImagingControl import *
  File "C:\Users\<USERNAME>\Documents\Vision project\pyicic\IC_ImagingControl.py", line 7, in <module>
    from .IC_GrabberDLL import IC_GrabberDLL
  File "C:\Users\<USERNAME>\Documents\Vision project\pyicic\IC_GrabberDLL.py", line 12, in <module>
    class IC_GrabberDLL(object):
  File "C:\Users\<USERNAME>\Documents\Vision project\pyicic\IC_GrabberDLL.py", line 23, in IC_GrabberDLL
    _ic_grabber_dll = windll.LoadLibrary('tisgrabber.dll')
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python37-32\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
[Finished in 0.323s] `

Anyone know how to resolve this OSError?

**Comment by morefigs** [comment]
It looks as if `tisgrabber.dll` or one of its dependencies cannot be found. Make sure the folder that contains those files is in your Windows PATH variable.
